
version: '2'
services:
  zookeeper:
    image: zookeeper:3.5.9
    ports:
      - "12181:2181"
    networks:
      - host
  kill:
    image: killsystem-kill:1.0
    container_name: kill01
    ports:
      - "8081:8081"
    environment:
      - spring.application.name=kill01

    networks:
      - host
    depends_on:
      - zookeeper
  payment:
    image: killsystem-pay:1.0
    container_name: pay01
    ports:
      - "8081:8081"
    environment:
      - spring.application.name=payment01

    networks:
      - host
    depends_on:
      - zookeeper