
version: '2'
services:
  zookeeper:
    image: zookeeper:3.5.9
    container_name: zookeeper_container
    ports:
      - "2181:2181"
    networks:
      - kafkanet
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka_container
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 47.102.46.78
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafkanet
    depends_on:
      - zookeeper
  mysql_miaosha:
    #docker run --name mysqlinstance -p 3306:3306 \
    #-e MYSQL_ROOT_PASSWORD=123456 \
    #--restart=always -d mysql:5.7.33
    build:
      context: .
      dockerfile: DockerfileMysql
    image: includenomysql:1.0.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    depends_on:
      - kafka
    
  redis:
    #docker run -itd --name redis_container -p 6379:6379 redis:6.0.13 redis-server --appendonly yes --requirepass "redis123456"
    image: redis:6.0.13
    container_name: redis_container
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass "redis123456"
    depends_on:
      - kafka



networks:
  kafkanet:
    driver: bridge