# https://docs.github.com/en/actions/guides
# CI name , it will display on github's action page menu
name: BuildKillSystemImages
# trigger on which this CI should be run
on: # push operation is operate
  push:
    # here since my repository branch is named `main` , you should follow your own repository like `master`
    branches: [main,dev]
# CI enviroment settings
env:
  STATE_RELEASE_VERSION: "1.0" # version
  TAG_NAME: "killsystem" #tag 只能小写开头
  java-version: "11"
jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest # use latest ubuntu to run the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java-version }}
      - name: Build with Maven
        run:
          mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: show files
        run: ls -a
      - name: Output Docker info
        run: docker info
      - name: docker buildx
        run: docker buildx create --use --name mybuilder
      - name: Sets build date
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #版本号第一位不允许空格
      - name: Build KillSystem/cloudkill Image to Docker Hub
        id: docker_build_1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: cloudkill/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: "includeno/${{ env.TAG_NAME }}-kill:latest,includeno/${{ env.TAG_NAME }}-kill:${{ env.STATE_RELEASE_VERSION }}"
          push: true
      - name: Build KillSystem/payment Image to Docker Hub
        id: docker_build_2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: payment/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: "includeno/${{ env.TAG_NAME }}-pay:latest,includeno/${{ env.TAG_NAME }}-pay:${{ env.STATE_RELEASE_VERSION }}"
          push: true
      - name: Build KillSystem/killsystem-api Image to Docker Hub
        id: docker_build_2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: killsystem-api/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: "includeno/${{ env.TAG_NAME }}-api:latest,includeno/${{ env.TAG_NAME }}-api:${{ env.STATE_RELEASE_VERSION }}"
          push: true